services:
  # add the mssql server service to the docker-compose.yml file
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      DB_NAME: "user_management_and_webscrapping"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    expose:
      - "1433"

volumes:
  db-data:
